import { Resend } from 'resend';
import { config } from '../config';
import { DailySummary } from '../types';

export class EmailService {
  private resend: Resend;
  private fromEmail: string;
  private managerEmails: string[];

  constructor() {
    this.resend = new Resend(config.resend.apiKey);
    this.fromEmail = config.resend.fromEmail;

    // Support multiple manager emails (comma-separated in .env)
    const managerEmailString = config.resend.managerEmail;
    this.managerEmails = managerEmailString
      .split(',')
      .map(email => email.trim())
      .filter(email => email.length > 0);

    if (this.managerEmails.length === 0) {
      console.warn('⚠️  Warning: No manager emails configured!');
    } else {
      console.log(`📧 Email configured for ${this.managerEmails.length} recipient(s)`);
    }
  }

  async sendDailySummary(summary: DailySummary): Promise<void> {
    const htmlContent = this.generateEmailHTML(summary);

    try {
      // Send to all configured manager emails
      const emailPromises = this.managerEmails.map(email =>
        this.resend.emails.send({
          from: this.fromEmail,
          to: email,
          subject: `📊 Daily Chat Summary - ${summary.date} - Shoreline Dental`,
          html: htmlContent,
        })
      );

      await Promise.all(emailPromises);

      console.log(`✅ Daily summary email sent successfully for ${summary.date}`);
      console.log(`   Recipients: ${this.managerEmails.join(', ')}`);
    } catch (error) {
      console.error('❌ Error sending email:', error);
      throw error;
    }
  }

  private generateEmailHTML(summary: DailySummary): string {
    // Handle "No Chats" case
    if (summary.totalConversations === 0) {
      return `
        <!DOCTYPE html>
        <html>
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
        </head>
        <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #374151; max-width: 800px; margin: 0 auto; padding: 20px;">
          <div style="background: linear-gradient(135deg, #2C5F8D 0%, #4A90A4 100%); padding: 30px; border-radius: 10px; margin-bottom: 30px;">
            <h1 style="color: white; margin: 0;">📊 Daily Chat Summary</h1>
            <p style="color: #E5F4F9; margin: 5px 0 0 0; font-size: 18px; font-weight: 600;">Shoreline Dental Chicago</p>
            <p style="color: #E5F4F9; margin: 10px 0 0 0;">${summary.date}</p>
          </div>

          <div style="background: #f0f9ff; padding: 30px; border-radius: 10px; border-left: 4px solid #2C5F8D; margin-bottom: 30px; text-align: center;">
            <h2 style="color: #2C5F8D; margin-top: 0; font-size: 24px;">😴 No Chats Overnight</h2>
            <p style="font-size: 16px; color: #1f2937; margin: 20px 0;">
              The chatbot was active and available, but no visitors initiated conversations during the overnight period.
            </p>
            <p style="font-size: 14px; color: #6b7280; margin: 15px 0;">
              ✅ Chatbot is functioning normally<br>
              ✅ Ready to assist patients when they visit
            </p>
          </div>

          <div style="background: #f9fafb; padding: 20px; border-radius: 8px; margin-bottom: 30px;">
            <p style="color: #6b7280; font-size: 14px; text-align: center; margin: 0;">
              This is normal and expected during low-traffic hours. The system will continue monitoring and will send a full summary when chats occur.
            </p>
          </div>

          <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #e5e7eb; text-align: center; color: #6b7280; font-size: 14px;">
            <p style="margin: 10px 0;">📍 Shoreline Dental Chicago | 737 N Michigan Ave, Suite 910, Chicago, IL 60611</p>
            <p style="margin: 10px 0;">📞 (312) 266-3399 | 🌐 www.shorelinedentalchicago.com</p>
            <p style="margin: 20px 0 0 0; font-size: 12px; color: #9ca3af;">This is an automated summary generated by the Shoreline Dental AI Chatbot.</p>
          </div>
        </body>
        </html>
      `;
    }

    // Generate To-Do Items section
    const todoItemsHTML = summary.todoItems.length > 0
      ? `
        <h2 style="color: #1f2937; margin-top: 40px;">📋 To-Do Items for Today</h2>
        <div style="background: #fffbeb; padding: 20px; border-radius: 8px; border-left: 4px solid #f59e0b; margin-bottom: 30px;">
          <ul style="line-height: 2; margin: 0; padding-left: 20px;">
            ${summary.todoItems.map(item => `<li style="margin-bottom: 8px;"><strong>${item}</strong></li>`).join('')}
          </ul>
        </div>
      `
      : `
        <h2 style="color: #1f2937; margin-top: 40px;">📋 To-Do Items for Today</h2>
        <div style="background: #f0fdf4; padding: 20px; border-radius: 8px; border-left: 4px solid #10b981; margin-bottom: 30px;">
          <p style="color: #059669; font-style: italic; margin: 0;">✅ No specific action items identified - all inquiries were handled by the chatbot.</p>
        </div>
      `;

    const conversationsHTML = summary.conversations.map((conv, idx) => {
      const messagesHTML = conv.messages.map(msg => `
        <div style="margin-bottom: 10px; padding: 10px; background: ${msg.role === 'user' ? '#f3f4f6' : '#eff6ff'}; border-radius: 5px;">
          <strong style="color: ${msg.role === 'user' ? '#1f2937' : '#1e40af'};">${msg.role === 'user' ? 'Customer' : 'Assistant'}:</strong>
          <p style="margin: 5px 0 0 0;">${msg.content}</p>
          <small style="color: #6b7280;">${new Date(msg.timestamp).toLocaleTimeString()}</small>
        </div>
      `).join('');

      return `
        <div style="margin-bottom: 30px; padding: 20px; border: 1px solid #e5e7eb; border-radius: 8px;">
          <h3 style="color: #1f2937; margin-top: 0;">Conversation ${idx + 1}</h3>
          <p style="color: #6b7280; font-size: 14px;">Started: ${new Date(conv.startTime).toLocaleString()}</p>
          ${messagesHTML}
        </div>
      `;
    }).join('');

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
      </head>
      <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; line-height: 1.6; color: #374151; max-width: 800px; margin: 0 auto; padding: 20px;">
        <div style="background: linear-gradient(135deg, #2C5F8D 0%, #4A90A4 100%); padding: 30px; border-radius: 10px; margin-bottom: 30px;">
          <h1 style="color: white; margin: 0;">📊 Daily Chat Summary</h1>
          <p style="color: #E5F4F9; margin: 5px 0 0 0; font-size: 18px; font-weight: 600;">Shoreline Dental Chicago</p>
          <p style="color: #E5F4F9; margin: 10px 0 0 0;">${summary.date}</p>
        </div>

        <div style="background: #f9fafb; padding: 20px; border-radius: 8px; margin-bottom: 30px;">
          <h2 style="color: #1f2937; margin-top: 0;">📈 Overview</h2>
          <p><strong>Total Conversations:</strong> ${summary.totalConversations}</p>
          <p><strong>Total Messages:</strong> ${summary.totalMessages}</p>
        </div>

        <h2 style="color: #1f2937;">📊 AI Summary & Analysis</h2>
        <div style="background: #f0f9ff; padding: 20px; border-left: 4px solid #2C5F8D; border-radius: 8px; margin-bottom: 30px;">
          <p style="line-height: 1.8; margin: 0;">
            ${summary.summary}
          </p>
        </div>

        ${todoItemsHTML}

        <h2 style="color: #1f2937; margin-top: 40px;">💬 Complete Chat History (Raw Format)</h2>
        <p style="color: #6b7280; font-size: 14px; margin-bottom: 20px;">Full transcripts of all conversations with timestamps:</p>
        ${conversationsHTML}

        <div style="margin-top: 40px; padding-top: 20px; border-top: 2px solid #e5e7eb; text-align: center; color: #6b7280; font-size: 14px;">
          <p style="margin: 10px 0;">📍 Shoreline Dental Chicago | 737 N Michigan Ave, Suite 910, Chicago, IL 60611</p>
          <p style="margin: 10px 0;">📞 (312) 266-3399 | 🌐 www.shorelinedentalchicago.com</p>
          <p style="margin: 20px 0 0 0; font-size: 12px; color: #9ca3af;">This is an automated summary generated by the Shoreline Dental AI Chatbot.</p>
        </div>
      </body>
      </html>
    `;
  }
}

export const emailService = new EmailService();
